### PR TITLE
First set of tests

### PR DESCRIPTION
**Pull request by ShawnHymel**
Moved from original circuitpython repo. Initial set of tests for onboard LED, GPIO, battery/voltage monitor pins, UART, SPI, I2C, SD card (SPI), and SD chip detect (CD) pin.

### CODE REVIEW

**Comment by ShawnHymel** [comment]
@tannewt tagging you :)

**Review by tannewt — CHANGES_REQUESTED** [review]
Thanks for making new PRs! Please remove the mpy files because they will be auto generated.

@kattni @sommersoft what do you think about us renaming the files in source as examples so they get bundled as such. That way you just download a bundle onto a new board and can test it.

**Comment by ShawnHymel** [comment]
@tannewt Removed .mpy files

**Comment by kattni** [comment]
@tannewt I don't understand what you're suggesting. Please clarify.

**Comment by sommersoft** [comment]
I _think_ I understand what @tannewt is saying, but I'll wait for his clarification.

Further, is this going into the bundle? If so, it will need some cookiecutter action applied, I imagine. If not, I guess we could write an "adabot-like" to handle local bundling/releasing.

**Comment by tannewt** [comment]
@ShawnHymel Thanks!

@kattni @sommersoft I'm thinking we rename the source folder to examples and the individual files to match our naming scheme for examples. That way they'll end up in the bundle and not need any extra install when testing on a new board. Yes, that will need cookiecutter-ification but I wasn't going to ask Shawn to do that in this PR. Should we just merge and rename the files when we cookiecutter?

**Comment by kattni** [comment]
@tannewt As long as every file begins with `boardtest_` I'm ok with it. I want the files renamed before we rename the source folder to examples.

If you want this merged before that, we should wait to rename the source folder until we cookiecutter it.

**Comment by sommersoft** [comment]
In re-visiting my thoughts, I see it a little differently.

Everything in `source` is more akin to a package and would be better in `/adafruit_boardtest`, and `main.py` is the example since it wraps usage of the `_test` scripts.

As a "non-voting" member, my thoughts should be weighted. :smile:

**Review by tannewt — APPROVED** [review]
I'm approving and merging so @ShawnHymel can move forward.

I agree with @sommersoft about it being a package but also think we should be able to run each test individually.

**Comment by tannewt** [comment]
I also agree with @kattni and am leaving the naming as is.

**Pull request merged**
